### ISSUE TITLE
Add help account to empty reciever channel

### ISSUE THREAD

**Issue by bbonkr** [iCloudHospital/CloudHospital.UnreadMessageReminderJob#29]
## Description

When user (client) sent a message, does not exist receiver, Add help account this group channel.

### Procedure of choosing manager:

1. Get Hospital data from database with hospitalId
2. Check webSiteUrl in Hospital
3. Use manager id
    1. webSiteUrl is null or empty or `https://icloudhospital.com`: Use help@icloudhospital.com
    2. webSiteUrl is not null and not empty and not `https://icloudhospital.com`: Get manager id from database with hospitalId (ManagerAffiliation)

`HospitalId` from Channel.CustomType

Hospital.webSiteUrl is not null:

```sql
select
    top 1
    b.UserName,
    a.UserId
from 
    ManagerAffiliations a 
JOIN
    Users b 
ON
    a.ManagerId = b.Id
WHERE
    HospitalId = `@HospitalId`
;
```

Invite ManagerId of top 1 from query result.

Hospital.webSiteUrl is null:

Invite `help@icloudhospital.com` (`0433bf8c-0f90-4d42-866f-4e5fe36b3237`)

## Reference

- https://github.com/iCloudHospital/cloudhospital.admin/issues/841
- https://github.com/iCloudHospital/CloudHospital.Api/issues/2103

**Comment by bbonkr** [comment]
@hyounoo 

Please review Procedure of choosing manager.

And let me know if you have any considerations.

**Comment by hyunoosung** [comment]
@bbonkr The select query result might be not 'help@icloudhospital.com'

How about this flow instead?
```cs
// Check if the hospital has WebSiteUrl property
if (WebSiteUrl == null)
{
    // Get help@icloudhospital.com(hard coded) 
}
else if (WebSiteUrl != null)
{
    // Select top 1 Manager with above query
}
```

This is because SaaS client manager can be invited to group channel more than 2000 times eventually.

**Comment by bbonkr** [comment]
@hyounoo 

You said:

1. Get Hospital data from database with hospitalId
1. Check webSiteUrl in Hospital
1. Use manager id
    1. webSiteUrl is null or empty or `https://icloudhospital.com`: Use [help@icloudhospital.com](mailto:help@icloudhospital.com)
    1. webSiteUrl is not null and not empty and not `https://icloudhospital.com`: Get manager id from database with hospitalId (ManagerAffiliation)

Is it right?

**Comment by hyunoosung** [comment]
@bbonkr Yes

**Comment by bbonkr** [comment]
@hyounoo 

Thank you for your review.

**Comment by bbonkr** [comment]
@hyounoo 

Configuration added. 

INT: 

```json
{
  {    
    "name": "SendBirdAppId",
    "value": "D39AC198-F710-498F-8D68-46793C09293E",
    "slotSetting": false
  },
  {
    "name": "HelpUserId",
    "value": "0433bf8c-0f90-4d42-866f-4e5fe36b3237",
    "slotSetting": false
  }
}

```

PRD:

```json
{
  {
    "name": "SendBirdAppId",
    "value": "164B502D-D1AE-4243-AA99-BBC1FEC2BA4A",
    "slotSetting": false
  },
  {
    "name": "HelpUserId",
    "value": "0433bf8c-0f90-4d42-866f-4e5fe36b3237",
    "slotSetting": false
  }
}
```
