### ISSUE TITLE
SendbirdService not working

### ISSUE THREAD

**Issue by bbonkr** [iCloudHospital/CloudHospital.UnreadMessageReminderJob#31]
## Description

![image](https://user-images.githubusercontent.com/3590545/213135098-9dbd5cbf-0520-4d58-b42d-fa541bb5234a.png)

Query for logs on Application Insights:

1. Find log concerned; sender nickname is `YUNJI CHTEST`

```plaintext
traces
| where timestamp >= (ago(3h))
| where cloud_RoleName == 'unreadmessagereminder-int'
| where message contains "YUNJI" 
| order by timestamp desc 
```

2. Query for log with operation_id

```plaintext
traces
| where timestamp >= (ago(3h))
| where cloud_RoleName == 'unreadmessagereminder-int'
| where operation_Id == 'caffa946eddfa916cbc0f2cb61170e1e'
| order by timestamp desc 
```

3. Found failure message

```plaintext
❌ Fail to invite manager to group channel. channel=7706c443-e017-432a-1b09-08d7c4bd83b4--58c24eb8-cffd-4b84-b601-9a951d01f13a;manager=83aafc61-1082-4327-8c8e-d58013ebcae4;message=Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
```
 
### Fix SendbirdService

Remove content-type of request header

## Reference

- https://github.com/iCloudHospital/cloudhospital.admin/issues/841
- https://github.com/iCloudHospital/cloudhospital.admin/issues/841#issuecomment-1386687258

**Comment by bbonkr** [comment]
Hospital exists that webSiteUrl is `https://icloudhospital.com`

```plaintext
❌ Fail to invite manager to group channel. channel=5aeaf7b1-5591-44e1-c191-08d7c4cd15e0--58c24eb8-cffd-4b84-b601-9a951d01f13a;manager=83aafc61-1082-4327-8c8e-d58013ebcae4;message=Fail to invite user: {"error":true,"message":"\"User\" not found.","code":400201}
```

**Comment by bbonkr** [comment]
Use help user id when hospital websiteurl is one of `https://int.icloudhospital.com`, `https://icloudhospital.com`

**Comment by hyunoosung** [comment]
I’ve updated hospital url to int.icloudhospital.com on int database
